FROM apache/airflow:latest

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    APP_HOME=/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*
    
COPY requirements.txt ${APP_HOME}
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt



WORKDIR ${APP_HOME}

CMD ["bash"]