x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile

  env_file:
    - ./config/enviroments/.env.env.airflow
    - ./config/enviroments/.env
  
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./config:/opt/airflow/config
    - airflow_logs:/opt/airflow/logs
    
  depends_on:
    - postgres

  networks:
    airflow_net:    

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      airflow_net:
        ipv4_address: 172.25.0.2          

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: >
      bash -c "airflow db init &&
               airflow users create --username admin --firstname Admin \
               --lastname User --role Admin --email admin@example.com --password admin"

  webserver:
    <<: *airflow-common
    command: webserver
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-init
    networks:
      airflow_net:
        ipv4_address: 172.25.0.3
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@172.25.0.2/airflow


  scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    depends_on:
      - webserver
    networks:
      airflow_net:
        ipv4_address: 172.25.0.4
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@172.25.0.2/airflow



networks:
  airflow_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24

volumes:
  postgres_data:
  airflow_logs: